investiage SRLDA crash

diff --git a/tools/toolchain/Dockerfile.intel b/tools/toolchain/Dockerfile.intel
--- a/tools/toolchain/Dockerfile.intel
+++ b/tools/toolchain/Dockerfile.intel
@@ -44,13 +44,61 @@ RUN source /opt/intel/oneapi/setvars.sh \
 
 #TODO: libint's make install is broken :-(
 
+#WORKDIR /workspace/cp2k
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && make ARCH=Linux-x86-64-intel-minimal VERSION=psmp -j
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && ulimit -s unlimited \
+#    && (( $(df --output=size  /dev/shm | tail -1)  > 1000000 )) \
+#    && make ARCH=Linux-x86-64-intel-minimal VERSION=psmp test TESTOPTS="-maxtasks 32"
+
+
 WORKDIR /workspace/cp2k
 COPY Linux-x86-64-intel.ssmp arch/
 RUN source /opt/intel/oneapi/setvars.sh \
     && make -j ARCH=Linux-x86-64-intel VERSION=ssmp
-
 RUN source /opt/intel/oneapi/setvars.sh \
-    && make ARCH=Linux-x86-64-intel VERSION=ssmp test TESTOPTS="-restrictdir QS/regtest-hfx-wfn-fitting"
+    && ulimit -s unlimited \
+    && (( $(df --output=size  /dev/shm | tail -1)  > 1000000 )) \
+    && make ARCH=Linux-x86-64-intel VERSION=ssmp test TESTOPTS="-maxtasks 32"
+# Failing tests: QMMM/QS/regtest-4/acn-conn-1.inp and QS/regtest-hfx-wfn-fitting/CH4-rsLDA.inp
+
+
+#===============================================================================
+#(( $(df --output=size  /dev/shm | tail -1)  > 1000000 )) || echo "false"
+
+#WORKDIR /workspace/cp2k
+#COPY Linux-x86-64-intel.ssmp arch/
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && make -j ARCH=Linux-x86-64-intel VERSION=ssmp
+#
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && make ARCH=Linux-x86-64-intel VERSION=ssmp test TESTOPTS="-restrictdir QS/regtest-hfx-wfn-fitting"
+
+
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && cd tests/QS/regtest-hfx-wfn-fitting \
+#    && OMP_NUM_THREADS=1 ../../../exe/Linux-x86-64-intel/cp2k.ssmp CH4-rsLDA.inp
+
+#RUN apt-get update -qq \
+#    && apt-get install -qq --no-install-recommends vim \
+#    && rm -rf /var/lib/apt/lists/*
+
+#RUN apt-get update -qq \
+#    && apt-get install -qq --no-install-recommends valgrind \
+#    && rm -rf /var/lib/apt/lists/*
+
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && cd tests/QS/regtest-hfx-wfn-fitting \
+#    && ulimit -s unlimited \
+#    && OMP_NUM_THREADS=1 valgrind ../../../exe/Linux-x86-64-intel/cp2k.ssmp CH4-rsLDA.inp
+
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && make ARCH=Linux-x86-64-intel VERSION=ssmp test TESTOPTS="-restrictdir QS/regtest-hfx-wfn-fitting"
+
+#COPY Linux-x86-64-intel.psmp arch/
+#RUN source /opt/intel/oneapi/setvars.sh \
+#    && make -j ARCH=Linux-x86-64-intel VERSION=psmp
 
 #===============================================================================
 
